spring:
  application:
    name: demochapter02

person:
  hobby:
    - play
    - read
    - sleep
  family:
    - father
    - mother
  map:
    k1: v1
    k2: v2
  pet:
    type: dog
    name: kity
  id: 111
